### PR TITLE
Correctly handle test timeouts (#54)

### LINKED ISSUE #54: Tests are skipped if enough data is written to stdout
TL;DR tests should fail if they exit because of excessive output.

I'm mentoring a student on the Rust track who submitted this code for the lasagna exercise:
```
pub fn remaining_minutes_in_oven(actual_minutes_in_oven: i32) -> i32 {
    let minutes_left_in_oven = expected_minutes_in_oven() - actual_minutes_in_oven;
     while actual_minutes_in_oven <= 40 {
         println!("The remaining minutes in the oven is: {} ", minutes_left_in_oven);
     }
    return minutes_left_in_oven
}
```

Of course this code will loop forever, printing each time. After [some discussion](https://github.com/exercism/rust/issues/1536) it seems that a test is skipped if enough data is written to stdout. For this exercise Exercism shows "five tests passed" when there are six tests for this exercise. If you simply loop without printing anything the tests fail with a timeout as expected. I've reproduced this with a different exercise in Rust, but I assume it affect any language capable of writing fast enough to beat the timeout.

It's not uncommon for a student to accidentally submit code that gets stuck in a loop, and it'll be confusing for them if the tests pass just because they happen to have a print statement in there.

Edit: BTW I don't recommend running the above code locally for obvious reasons!

### PR DESCRIPTION
**Pull request by ZloeSabo**
This PR fixes #54. The actual issue is not the output size; The runner currently does not support test timeouts. 

Currently, the rust test suite itself does not support setting time limits to abort a test that runs for too long (see rust-lang/rfcs#2798). 

There's an option `--ensure-time`, but it only controls the time threshold to mark a test failed (generates event like `{ "type": "test", "name": "tests::test_empty_a", "event": "failed", "exec_time": 7.000362262, "reason": "time limit exceeded" }`) and does not abort the test itself. 

So I see three ways of dealing with badly written code:

* wait for cargo to abort the hanging test after 120 secs. In this case, it emits timeout event like this: `{ "type": "test", "event": "timeout", "name": "test_empty" }` that could be parsed with the transformer. The downside is that for two minutes the test runner is going to be blocked. Not sure how bad it is for excercism, but generally blocked workers are no good.  :smile: 
* implement a custom test harness with support for test timeouts. While rust supports this, it looks to me like a very labor-intensive way to solve the problem.
* use an external utility to abort the test runner after some time. 

It seems to me, that the latter is currently the best way to solve the issue. I've taken the inspiration from the [rust playground](https://github.com/integer32llc/rust-playground/blob/master/compiler/base/entrypoint.sh) and changed the code to return `{status: "error", message:"Tests timed out"}` if the test suite does not finish after 5 sec.

Given the speed of rust, a timeout of 5 seconds seems reasonable to me, but please let me know if some shorter/longer fits better.

### CODE REVIEW

**Comment by iHiD** [comment]
@ZloeSabo Thanks so much for this! It requires a review by @ErikSchierboom, who's on his summer break and won't be back for 2 more weeks, so I'll have to ask for your patience before we get this merged. But please know how much we appreciate it!

**Review by ErikSchierboom — COMMENTED** [review]
It works great! Just a couple of tiny nits.

**Comment by jovv** [comment]
This seems near completion with minimal effort to fix the PR comments. What would be the recommended way to contribute so it can be merged?

**Comment by ErikSchierboom** [comment]
I currently have fairly limited time, so it'll take me a while to be able to review this. Sorry.

File: bin/run.sh [hunk 1]
```diff
@@ -54,3 +54,7 @@ cargo +nightly test \
 if grep -q "probable build failure" "$output_path"/results.json; then
    jq -n --rawfile m "$output_path"/results.out '{status: "error", message:$m}' > "$output_path"/results.json
 fi
+
+if grep -q "timeout: sending signal TERM" "$output_path"/results.out; then
```
[the remark this answers is not in the document]
Comment (ZloeSabo) [reply bin/run.sh]: I've changed the code a little with `elif`.
Basically, the trick is there is no test report output after the test timeout, so the transformer generates a generic "probable build failure" message.

So, to display the more specific message for timeouts either we need to make timeout and generic error messages generation mutually exclusive (as I changed it now) or overwrite the generic message (as I made it originally). It's also technically possible to add support for timeouts output to the transformer, but that's complicated to implement.

**Comment by ZloeSabo** [comment]
Hey @jovv @ErikSchierboom! Updated the PR. Sorry, that was a somewhat hectic time for me and I didn't really have time to look at this before.

File: bin/run.sh [hunk 2]
```diff
@@ -39,7 +39,7 @@ if jq --exit-status '.custom?."test-in-release-mode"?' "$solution_path"/.meta/co
     release="--release"
 fi
 
-cargo +nightly test \
+timeout -v 5s cargo +nightly test \
```
Comment (ErikSchierboom) [inline bin/run.sh:42]: Our internal time out for the test runner is 20 seconds. I think we'll probably want to be somewhat close-ish to that timeout limit. Maybe crank this up to 15 seconds? If there are no objections, I'm happy to merge this after that change.

**Review by ErikSchierboom — COMMENTED** [review]
Finally had time to review! Sorry about the wait. One small comment.

File: bin/run.sh (hunk 2 above)
Comment (ZloeSabo) [reply bin/run.sh]: :heavy_check_mark: Done

**Review by ErikSchierboom — APPROVED** [review]
